### ISSUE TITLE
Section 6.1 Design Goals - discussion...

### ISSUE THREAD

**Issue by martchcl** [trustoverip/TechArch#16]
CONTENT BEING MOVED:

> With regard to the first design goal, establishing trust between parties requires that each party develop confidence in the following properties of their relationship:
> 
> Authenticity: is the receiver of a communication able to verify that it originated from the expected sender?
> Integrity: is the receiver able to verify that a communication is complete and has not been tampered with?
> Confidentiality: is the contents of a communication protected so only authorized parties have access?
> Privacy: will the expectations of each party with respect to usage of shared information be honored by the other parties?
> 

DISCUSSION:

Sam Smith - 
Authenticity is not possible without integrity. Authenticity assumes integrity. So integrity is not an independent design goal. Therefore there is no reason to include integrity in this list. Maybe an informative note might help to explain why integrity is subsumed by authenticity. Absent that at the very least integrity comes before authenticity in this list since as it says the ordering matters and integrity is clearly out of order.    A digital signature includes in it a digest of the item being signed therefore the signature will not verify if the item has been tampered with.   Putting integrity in this list confuses the idea that there is a trade-off being made by the ordering of the items. There is no trade-space between integrity and authenticity. Indeed it is non-sensical to talk about authenticity of data or authenticated data unless integrity is assumed.  If you say authenticity you get integrity for free. It may be that there is confusion with the definition of authenticity.  The english dictionary lists several definitions of authenticity or authentic. The ToIP stack by definition is talking about authentic data being transmitted over the internet and not something else.   The only definition that applies is  this one:  of undisputed origin, having an origin supported by unquestionable evidence; authenticated; verified:

In the context of
Show less
Samuel Smith
Samuel Smith
11:25 AM Yesterday
In the context of data being sent over the internet a more precise definition of authenticity with respect to data is data that is securely attributable to its source.  Data that has been tampered with cannot be securely attributed to its source. What constitutes as a source modulates the mechanisms for secure attribution but does not change the fact that integrity is assumed and authenticity depends on integrity not the other way around.

**Comment by neiljthomson** [comment]
If Authenticity and Integrity are to be mentioned, they should point to complying with the Design Principles for ToIP, which are to include coverage of Integrity, Authenticity, Non-Repudiation, Privacy and Confidentiality. Neil Thomson to review how to cover these topics (combination of Design Principles doc, and the Terms wiki (ToIP or Tech Arch).

**Comment by talltree** [comment]
This issue needs to be merged with #10. It is the same discussion.

**Comment by talltree** [comment]
Closing this issue to consolidate it with #10.
