### ISSUE TITLE
6.3 High-Level System Architecture - FIGURE 6

### ISSUE THREAD

**Issue by martchcl** [trustoverip/TechArch#18]
> COMMENT ON IMAGE

Allan Thomson
10:48 18 Aug

We discussed a new variant of this diagram to help highlight the Intermediary relationship.

Drummond Reed
02:16 25 Aug
Allan, can you remember what the specific suggestion(s) were? Then we can produce a revised version.

Drummond Reed
10:40 25 Aug
WENJING recalls that this diagram uses two Intermediary systems but shows only one Supporting System. Wenjing will update.

Darrell O'Donnell
10:40 25 Aug
@[drummond.reed@avast.com](mailto:drummond.reed@avast.com) or @[wenjing.chu@futurewei.com](mailto:wenjing.chu@futurewei.com) this diagram isn't in the slide deck where we have consolidated the diagrams that are in use.

Drummond Reed
17:40 25 Aug
@[darrell.odonnell@continuumloop.com](mailto:darrell.odonnell@continuumloop.com) None of Wenjing's diagrams are currently in that deck. That's one of his action items (as he goes through updating them) to place them in that deck.

Drummond Reed
03:18 26 Aug
@[chu.wenjing@gmail.com](mailto:chu.wenjing@gmail.com) to revise his diagram and place in the TAS Source Diagrams Google Slides deck.

**Comment by talltree** [comment]
This issue is about the same diagram being discussed in #31. Suggest we make a reference to this issue there and then close this issue.

**Comment by darrellodonnell** [comment]
I am good with that.

**Comment by talltree** [comment]
My mistake, @darrellodonnell. Issue #31 is about Figure 4, and this issue is about Figure 6. I am assigning to @wenjing who did the original (who can consult @allant0 about the suggested changes).

**Comment by talltree** [comment]
@wenjing will propose a revision to the figure.

**Comment by wenjing** [comment]
This comment was copied from the old Google doc. It had been fixed already during the moving to Github back in Sept. The relevant commit is: https://github.com/trustoverip/TechArch/commit/00556f2e684316ea1e39570da0cbb2d8fc80210e.
@talltree @darrellodonnell please take a look. The change is about "Supporting Systems" - we now show two instances of supporting systems to be consistent with 2 instances of intermediary systems. I'll probably propose last call if there's no new comment.

**Comment by talltree** [comment]
We reviewed this together on [the 2022-11-10 TATF NA/EU meeting](https://wiki.trustoverip.org/display/HOME/2022-11-10+TATF+Meeting+Notes) and agreed with Wenjing that the figure had been updated to address the issue. Thus we are closing this issue as agreed on the call.
