### ISSUE TITLE
6.4 ToIP Identifiers - FIGURE 7

### ISSUE THREAD

**Issue by martchcl** [trustoverip/TechArch#20]
> COMMENT ON IMAGE

Jo Spencer
08:57 26 Aug
It feels like these should be  UML notation diagram.

Drummond Reed
11:44 26 Aug
Jo, I was thinking exactly that except did not want to require the reader to understand UML diagram notation (even though I expect most readers of this spec will have that knowledge). In any case, feel free to make such a replacement. (If that's not possible before the spec moves to GitHub, let's move this comment to GitHub and we'll make the change there.)

**Comment by RieksJ** [comment]
The "[Notations and Conventions](https://essif-lab.github.io/framework/docs/notations-and-conventions)" page has a [CC BY-SA 4.0 ](http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)  and can hence be freely reused (e.g. as an appendix). No need to learn UML (but you need to know about some general ideas, as generalization and such, but I'd expect of a tech arch doc to be sufficiently familiar with that).

**Comment by martchcl** [comment]
changes made, ok to close

**Comment by martchcl** [comment]
changes made, ok to close
