### ISSUE TITLE
10.3 Example 2 — KERI - FIGURE 13

### ISSUE THREAD

**Issue by martchcl** [trustoverip/TechArch#28]
> COMMENT ON IMAGE

Drummond Reed
03:44 24 Aug
TODO: Needs revised labels

**Comment by darrellodonnell** [comment]
done - @wenjing please update the TAS Source Diagrams deck with the new diagram.

https://docs.google.com/presentation/d/1lqaidE8hBA7Ona_-TnTCiOeLhCVRf_1m8ujBMuYtl7k/edit#slide=id.g146a4a06e34_0_70
