### ISSUE TITLE
Naming endpoint, supporting system and intermediary system

### ISSUE THREAD

**Issue by wenjing** [trustoverip/TechArch#3]
There were some discussions on the naming of these top level components in the architecture. On June 16, 2022 TF meeting, we settled tentatively on these:
- Endpoint System(s), which can be shortened to Endpoint(s)
- Supporting System(s)
- Intermediary System(s), which can be shortened to Intermediary or Intermediaries
We generally agreed to stick to "System", rather than Point or Node, as implementations can vary significantly and we chose to prefer precision.
This issue is created to keep track of any additional discussions as needed.

**Comment by talltree** [comment]
Closing this issue as it was settled per Wenjing's comment above.
