### ISSUE TITLE
Description of trust support missing supporting systems

### ISSUE THREAD

**Issue by wenjing** [trustoverip/TechArch#34]
In Section 8.2, the paragraph "Such proofs may require support from one or more Layer 1 Trust Support Functions and/or the invocation of one or more Layer 3 Trust Task Protocols. These steps are out-of-scope for the Layer 2 Trust Spanning Protocol." is missing the most important support - i.e. the Supporting Systems.

It should be rephrased as "Such proofs may require support from one or more Layer 1 Trust Support Functions within the Endpoint, and/or support of one or more Supporting Systems outside of the Endpoint, and/or the additional invocation of one or more Layer 3 Trust Task Protocols. These steps are out-of-scope for the Layer 2 Trust Spanning Protocol.".

**Comment by talltree** [comment]
+1 to this addition.

_Proposed label: `needs-PR`_

**Comment by andorsk** [comment]
@martchcl so is this viable for closing?  Shall I mark it for review to close?
