### ISSUE TITLE
TOIP Slack channel for TechArch?

### ISSUE THREAD

**Issue by RieksJ** [trustoverip/TechArch#35]
I was looking for a TOIP slack channel about TechArch, but could not find any. Is there any particular such channel where we can communicate? Or should we set it up?

**Comment by wenjing** [comment]
@RieksJ please join the Technology Architecture Task Force's slack channel: https://trustoverip.slack.com/archives/C02JT4GEJ75
I also updated the readme page to include the URL link. Closed.
