### ISSUE TITLE
Inclusion of Intermediary Systems

### ISSUE THREAD

**Issue by wenjing** [trustoverip/TechArch#4]
There were several comments & questions raised on the inclusion of Intermediary Systems in the architecture. 
This issue is created to continue on that discussion in Github.
My rephrase of the gist of these questions/comments is:
- Intermediary systems should be avoided because it goes against the decentralization principle (for a list of common reasons: liability, privacy, security, non-repudiation and end-to-end trust)
- Asks for examples

**Comment by wenjing** [comment]
Here is my response (June 16, 2022 TF meeting):

- Intermediary Systems are not absolutely required, in theory. However, most practical applications would require them. I believe they should be an important component of the architecture.
- Yes, any Intermediaries bring certain risks, but the Intermediaries as described in the architecture are not in the direct chain of trust. The corresponding section in the spec is to define it more precisely.
- Two examples:
     - didcomm2 mediator/relay: https://didcomm.org/book/v2/routing
     - DWN: https://identity.foundation/decentralized-web-node/spec/

**Comment by sankarshanmukhopadhyay** [comment]
>     * Two examples:
>       
>       * didcomm2 mediator/relay: https://didcomm.org/book/v2/routing
>       * DWN: https://identity.foundation/decentralized-web-node/spec/

Would it then be easier to use a definition/example pair to establish the scope of (and requirements from) systems which will be considered as "Intermediary Systems" for the purposes of the Technology Architecture Specification? At present the section in the draft has comments, but no text.

**Comment by wenjing** [comment]
This issue is NOT about what that section will/should cover, but whether or not the spec will include Intermediaries at all. There are some strongly worded comments AGAINST having Intermediaries. This issue is created to resolve that question.

**Comment by talltree** [comment]
I believe the comments above pre-date the addition of section 9 on Intermediary Systems. @wenjing, is this still an issue or can it be closed?

**Comment by wenjing** [comment]
I believe this issue is resolved with sufficient discussion and consensus. Move to last call.
