### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by andorsk** [trustoverip/TechArch#42]
https://docs.github.com/en/discussions

**Comment by andorsk** [comment]
Per the October 13 meeting, Github discussions to be turned on. @wenjing

**Comment by andorsk** [comment]
This was done: 
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/8604639/196149285-0236b8b3-fe5e-4460-8154-e24efe6cfebb.png">

**Comment by talltree** [comment]
Closing — last call period complete.
