### ISSUE TITLE
Provide Access Controls To Maintainers

### ISSUE THREAD

**Issue by andorsk** [trustoverip/TechArch#45]
This ticket is to determine and provide the correct access controls to the maintains of this repo, so that relevant parties are given the correct permissions to maintain the repo per their responsibilities. 

This was for example, an issue in https://github.com/trustoverip/TechArch/issues/37 where I needed the access to create labels, and did not have it.

**Comment by andorsk** [comment]
My suggestion is we have some governance "roles":

A proposal: 

1. Maintainer <- Tagging issues, Closing issues, Creating issues, Review, and merging PRs
2. Admins <- Has administrative power over the repo. These may include: adding issues, changing labels, updating permissions, blocking users if needed, etc.
3. Public <- Can always create issues, set up PR ( ON A FORK ). 

Nobody should be able to push directly to `master` IMO.

**Comment by andorsk** [comment]
Some important documentation that @talltree put up, which will help inform this is here: https://wiki.trustoverip.org/display/HOME/GitHub+Issues+Management+Process.

**Comment by andorsk** [comment]
TODO:  Provide actions for role. 
Drummond: 
Editors: Come up with permissions for the role. 
Permission to work with current admin Elisa for rights.

**Comment by andorsk** [comment]
@elisatrevino

**Comment by andorsk** [comment]
Proposed resolution: Revision to the wiki page with subgroup process edits. @talltree to lead that.

**Comment by andorsk** [comment]
Add needs editor review.
Action item: Fill out a table with details about the labels.

**Comment by a-fox** [comment]
This is resolved once the Contibuting & Governance files are merged, am I right?

**Comment by andorsk** [comment]
@a-fox yea...I think we during the call this gets hashed out and merged.
