### ISSUE TITLE
Fix old issues: Relabel all the existing issues with the correct labels and possibly assign

### ISSUE THREAD

**Issue by andorsk** [trustoverip/TechArch#47]
Based on https://github.com/trustoverip/TechArch/issues/37, go back and relabel all the existing issues with the appropriate label. Assign where it makes sense.

**Comment by andorsk** [comment]
@martchcl what's the status of this. It looks like it's done? Should it be transitioned to ready for closing?

**Comment by martchcl** [comment]
Yes its ready to close

**Comment by talltree** [comment]
@andorsk FYI the reason for the label change was to get this issue at the top of the priority list so we can finish it ASAP. I myself think it is complete, so I propose we close it on Thursday's TATF call (since that will be 5 days anyway).

**Comment by andorsk** [comment]
no problem. Sounds good. Agreed this should close.

**Comment by martchcl** [comment]
completed
