### ISSUE TITLE
Missing Section 11 - Endpoint System Interoperability

### ISSUE THREAD

**Issue by talltree** [trustoverip/TechArch#55]
Content required.

**Comment by talltree** [comment]
The text for this section [has been drafted in a Google doc](https://docs.google.com/document/d/1Lkd7G4fw7ruJqB_Knziu7_ziq2nRINcXE4p8P9WM60k/edit#bookmark=id.o31r428vufcd). Please review it there; then a PR will be created.

**Comment by andorsk** [comment]
closing based on 11/10 meeting at TAFT and PR #59

**Comment by andorsk** [comment]
Re-opening. There was a misunderstanding and this was not to be closed based on #59. @talltree to close

**Comment by talltree** [comment]
Closed by PR #67
