### ISSUE TITLE
Easy CLA vs. DCO

### ISSUE THREAD

**Issue by andorsk** [trustoverip/TechArch#63]
Comment on TechArch about investigating EasyCLA allowance to turn off DCO.

**Comment by andorsk** [comment]
I haven't used CLA before tbh, but from what I've seen, it should be able to replace DCO. 

https://github.com/electron/governance/issues/441

So the answer is yes, we can turn off DCO w/ CLA, but should understand that CLA imposes a tradeoff.

**Comment by andorsk** [comment]
I think this can be closed.

**Comment by talltree** [comment]
Agreed. Closing this issue.
