### ISSUE TITLE
TOIP Trust Spanning Layer Framework: Web 7.0 DID Communications/HTTP (DIDComm-ARM/HTTP) Profile (Example)

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/TechArch#83]
IMO, every TOIP TAS-compliant platform can define its own _TOIP Trust Spanning Framework Profile_. 

NOTE: There is actually no need to standardize each platform (i.e. document it on the TOIP website).  It's up to each individual platform release to demonstrate that it is TOIP TAS compliant.  _This is powerful._

Below is a copy of Web 7.0 DID Communications/HTTP (DIDComm-ARM/HTTP) TOIP Trust Spanning Framework Profile...

![image](https://user-images.githubusercontent.com/6101736/213926287-edb0ee1d-1de0-40a5-bdd7-38c5d1789a69.png)

NOTE: The **(Li)** annotations refer to the specific source layer in the 7-Layer Web 7.0 DIDComm-ARM model.

Hopefully, no further narrative is required.

CC: @dhh1128

**Comment by mwherman2000** [comment]
> proliferation of profiles doesn't add adoption/interop all that much

Please don't conflate _adoption_ with _interop_. They are related but in a vert orthogonal way.

For example, having multiple profiles actually encourages more innovation and hence, more adoption. It gives systems designers more options and hence increases adoption.

Interoperability only becomes a factor once we have adoption *and* deployment of multiple platforms, systems, and applications. Until there is 3-4 significant applications out there that need to interoperate, focusing on interop now IMO is a waste of time and resources.

**Comment by mwherman2000** [comment]
NOTE: The 2-party Credential Sender-Receiver Model (see https://github.com/trustoverip/TechArch/issues/84) is generic enough to be included in Layer 2. See the diagram at the top of this issue.

**Comment by mwherman2000** [comment]
Updated Web 7.0 DIDComm Hourglass Profile (the diagram at the top of the issue) to include artifacts from all 7 layers of the Web 7.0 DIDComm-ARM: https://hyperonomy.com/2022/12/12/welcome-to-web-7-0/

Updated "the 100 slides" to include the 7 layers of the Web 7.0 DIDComm-ARM (slides 96-113): https://docs.google.com/presentation/d/14YPhH66yfOetrSfuycuFOgQqxzGZ0b7H22EZDhilphU/edit#slide=id.g1447f0ca66d_0_0

**Comment by darrellodonnell** [comment]
> The 2-party Credential Sender-Receiver Model (see #84) is generic enough to be included in Layer 2.

In my world all of the credential activity is fully in Layer 3. Layer 2 is much narrower - creating the addressing and comms pipe, with a bare minimum of protocol that Layer 3 requires (commonly) to build upon.

**Comment by mwherman2000** [comment]
> 2-party Credential Sender-Receiver Model 

So let's rename it to the 2-party _Credential Exchange Sender-Receiver Model_ or something like that.  
The _exchange_ of credentials/messages is Layer 2.

**Comment by mwherman2000** [comment]
If we're going to be serious about this we also have to include and specify all of the different transports that DIDComm Communications can possibly run on.  It isn't just HTTP (REST/HTTP).  I've changed the title of this issue and the diagram at the top of this issue to reflect this.

This is further evidence why it is futile (in the real world) to try to standardize on a particular profile.  The goal of the TAS specification should be to standardize on the criteria/requirements for what defines a TOIP TAS-compliant profile ...and let developers/vendors create their own TOIP TAS-compliant implementations.

Here's the full Web 7.0 Layer 6 Web 7.0 DIDComm Agent Model from the Web 7.0 DIDComm-ARM (https://hyperonomy.com/2022/12/18/web-7-0-didcomm-agent-architecture-reference-model-didcomm-arm-0-40-december-18-2022/)...

![image](https://user-images.githubusercontent.com/6101736/213444388-97827caf-80ba-461d-b955-8bd9e9dd5afc.png)

The green box presents a detailed view of Web 7.0 DIDComm Network running over HTTP: Web 7.0 DIDComm Network Router Agents, etc.

The blue box is a sampling of all of the other potential transports that can support a Web 7.0 DIDComm Network ...just a sampling.  Each one of these needs it's own TOIP TAS-compliant profile documented.  Is TOIP going to undertake each of one these? I don't think so.

**Comment by mwherman2000** [comment]
> In my world all of the credential activity is fully in Layer 3. Layer 2 is much narrower - creating the addressing and comms pipe, with a bare minimum of protocol that Layer 3 requires (commonly) to build upon.

@darrellodonnell This is exactly what the Credential Sender-Receiver Model is all about ...the sending and receiving of a credential ...any credential.

**Comment by darrellodonnell** [comment]
and when I don't want a credential? (e.g. voice)

**Comment by mwherman2000** [comment]
> and when I don't want a credential? (e.g. voice)

Depends on your definition of a credential. 
In Web7.0, a credential is a collection of properties/attributes - i.e. a collection of name-value pairs.

**Comment by dhh1128** [comment]
>In Web7.0, a credential is a collection of properties/attributes - i.e. a collection of name-value pairs.

If that is your definition, then I feel like you are correct to place it at layer 2. However, I suggest that the word "credential" is a bad one to use for your definition. A credential is fundamentally evidence of entitlement (to status, to access). Your more generic concept is closer to what Sam Smith has been calling "verifiable data." It subsumes the specific type of verifiable data that is about evidence of entitlement, but it is quite a bit broader. That might be a good thing for the concept, insofar as it fits into a larger vision, but I suggest that it's a bad thing for the word "credential" -- it will create confusion.

**Comment by mwherman2000** [comment]
I believe it is best to characterize the TOIP 4-Layers as an architectural _framework_ and not as an architectural _model_. IMO, using the Web 7.0 DIDComm/HTTP Profile as a working example, the 4 layers of the TOIP 4-Layer aren't granular to be used as an architectural model/architectural reference model.

![Screenshot_20230120-044646](https://user-images.githubusercontent.com/6101736/213690907-bede1e34-bec0-445b-b971-23b6f54f6ec4.png)

**Comment by mwherman2000** [comment]
> Your more generic concept is closer to what Sam Smith has been calling "verifiable data."

A Credential is just a collection of properties/attributes... nothing more...a serialization of a collection of name-value pairs.
...with no implication that it is verifiable
...so Sam's term Verifiable Data is not synonymous with a Credential.

**Comment by darrellodonnell** [comment]
and a data stream?

**Comment by mwherman2000** [comment]
> and a data stream?

?? (stream is loaded word ... aka streaming)

**Comment by mwherman2000** [comment]
> I believe it is best to characterize the TOIP 4-Layers as an architectural _framework_ and not as an architectural _model_.
> 
> From the perspective of a software architect or developer and using the Web 7.0 DIDComm/HTTP Hourglass Profile as a working example, the 4 layers of the TOIP 4-Layer diagram aren't granular enough to be used as an architectural model/architectural reference model. It's a framework.
> 
> Architectural models like the Web 7.0 DIDComm-ARM can be mapped onto the TOIP 4-Layer architectural framework as illustrated at the top of this issue via the Web 7.0 DIDComm/HTTP Hourglass Profile (as an example).

Here's a recording where I describe the mapping of the Web 7.0 DIDComm-ARM to the TOIP TAS 4-Layer Hourglass Framework:
**[Mapping Web 7.0 DIDComm/HTTP Architecture Reference Model (DIDComm-ARM/HTTP) to TOIP TAS 4-Layer Hourglass Framework](https://youtu.be/re9e2vf20L8)**

**Comment by mwherman2000** [comment]
Re: Raw Credential Sender-Receiver Model

In Web 7.0, the following are equivalent:
- Raw Credential
- Collection of Properties where one property is an identifier 
- Collection of Attributes where one attribute is an identifier 
- Collection of Name-Value Pairs where one pair is an identifier 
- Collection of Claims where where one claim is an identifier 
- Collection of Assertions where one assertion is an identifier 

Cc: @dhh1128

**Comment by mwherman2000** [comment]
I created a new tutorial that summarizes the latest information from issues https://github.com/trustoverip/TechArch/issues/83 and https://github.com/trustoverip/TechArch/issues/84.  
If you have been following either thread, there is also some new data and graphics.  Check out
[Web 7.0 Trust Spanning Layer Framework 0.57](https://www.youtube.com/watch?v=rrFfuUHHmr4) (https://www.youtube.com/watch?v=rrFfuUHHmr4)
NOTE: It may be a few hours before YouTube has finished post-processing the video.

With this note, I'm closing both of the issues: https://github.com/trustoverip/TechArch/issues/83 and https://github.com/trustoverip/TechArch/issues/84.
