### ISSUE TITLE
Remove 3-party Issuer-Holder-Verifier diagram and replace with 2-party Raw Credential Sender-Receiver Model

### ISSUE THREAD

**Issue by mwherman2000** [trustoverip/TechArch#84]
Is the plan for the 3-party Issuer-Holder-Verifier credential exchange diagram going to remain in the TAS documentation? If so, read on...

The TAS specification doesn't need to have and shouldn't include the 3-party Issuer-Holder-Verifier diagram in the document. The flow depicted in this diagram is overly prescriptive and biased. It reflects only one restrictive use case: the use of Verifiable Credentials in an Identity Wallet scenario ...which is a small and restrictive use case when one considers the infinite number of ways verifiable credentials can be used in commercial business applications. e.g. https://hyperonomy.files.wordpress.com/2023/01/image-7.png

The diagram should be removed from this version of the specification.

The next most likely question is: What do we replace the 3-party model with?

We replace it with only what is necessary and sufficient for a technical specification: a 2-party Raw Credential Sender-Receiver Model. This is all the TAS spec needs/requires. For example, something like...

![image](https://user-images.githubusercontent.com/6101736/214305088-5e876966-6d8f-4802-8fc8-e36caea053c0.png)

UPDATE: Important tweaks have been made to the above diagram.

The topic of application-specific roles like Issuer, Holder, and Verifier needs to be removed to a separate application note or alternatively, to help minimize the number of changes to TAS specification, the following changes to the Terminology section can be adopted.

In any Terminology sections, the following additions are proposed to the following definitions:

holder - Holder is a combined [specialization ](https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045328)([aggregation](https://github.com/w3c/vc-data-model/issues/url)) of the Credential Receiver and the Credential Sender roles.
issuer - Issuer is a [specialization ](https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045328)of the Credential Sender role.
verifier - Verifier is a [specialization ](https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045328)of the Credential Receiver role.

Further, the Credential Sender and Credential Receiver roles can be [assigned ](https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045314)to either an Agent actor or a Wallet actor.

**Comment by mwherman2000** [comment]
Long shot: The Credential Sender-Receiver Model may actually be generic enough to belong in Layer 2.

**Comment by darrellodonnell** [comment]
@mwherman2000 Until we get IPR issues aligned I think we need to avoid looking at items that are under different / non-compatible IP regimes. While the input is valuable if it is not compatible with the IPR structures that we operate under I think it may put us off base.

**Comment by mwherman2000** [comment]
> @mwherman2000 Until we get IPR issues aligned I think we need to avoid looking at items that are under different / non-compatible IP regimes. While the input is valuable if it is not compatible with the IPR structures that we operate under I think it may put us off base.

The issue may have gotten contorted @darrellodonnell. I had to refresh my knowledge of the TOIP LF Charter and the historical issue related to incorporating the Sovrin Glossary into the TOIP Glossary.

1. There is nothing actually restrictive in Paragraph 7 of the TOIP LF Charter. (NOTE: It was impossible to find the final approved version of the charter - so I'm referencing this draft version: https://wiki.trustoverip.org/display/HOME/2021-03-10+Steering+Committee+Meeting+Page?preview=%2F74019%2F74026%2FExhibit+C+-+Version+5.0+JDF+Project+Charter+and+Working+Group+Charter.docx).

> 7. Conditions for Contributions.  A Steering Member, AssociateGeneral Member, or Contributor may not make any Contribution unless that Steering Member, AssociateGeneral Member or Contributor is the exclusive copyright owner of the Contribution or has sufficient copyright rights from the copyright owners to make the Contribution under the terms of this Project Charter and applicable Working Group Charter.  The Steering Member, AssociateGeneral Member, or Contributor must disclose the identities of all known copyright owners in the Contribution.

I/We meet all of the requirements of Paragraph 7.

2. The core issue relates to the copyright TOIP uses for a specific TOIP document and whether the copyright framework chosen by TOIP protects authors and other contributors who use the Creative Commons Attribution-ShareAlike 4.0 International Public License (https://creativecommons.org/licenses/by-sa/4.0/legalcode). In the case of the Sovrin Glossary scenario, the copyright on the TOIP Glossary wasn't sufficient to protect the Sovrin Foundation and its copyright on the Sovrin Glossary and its content.

So the ultimate question is: What has TOIP chosen as its documented and approved copyright statement for its documents, in general - as well as, more specifically, the TOIP TAS and TOIP TSL documents? ...back to you @darrellodonnell 

If this doesn't work out, I'm totally OK with that version of the situation but it's not my first choice.

**Comment by darrellodonnell** [comment]
Answering questions about the IP conditions that ToIP operates under is beyond what I can do.

@JFleenor can you help or find help here?

**Comment by mwherman2000** [comment]
The intent of the Raw Credential Sender-Receiver Model is to serve as the most basic architectural pattern from which new _[specializations](https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045328)_ can be derived; for example the 3-party Issuer-Holder-Verifier model.

**Comment by mwherman2000** [comment]
For completeness, below is a Layer 3 2-Party Verifiable Credential Sender-Receiver Model, also a specialization of the 2-Party Raw Credential Sender-Receiver Model...

![image](https://user-images.githubusercontent.com/6101736/214305510-0dd45dd0-897d-4cbe-9b93-8a1f946c6de7.png)

**Comment by talltree** [comment]
The three-party model applies to the roles of issuers, holders, and verifiers of digital credentials. It is a well-understood model in any system of credentials (even physical credentials) because the duties of an issuer relative to the job of issuing a credential are completely different than the duties of the verifier in verifying the credential — to say nothing of the holder role which is completely different from either issuer or verifier.

More importantly, the three-party model is called the "trust triangle" because it explains how transitive trust works, which we broke down into the constituent principles in the [Design Principles for the ToIP Stack V1.0](https://trustoverip.org/permalink/Design-Principles-for-the-ToIP-Stack-V1.0-2022-11-17.pdf). 

Furthermore, the ToIP Technology Architecture V1.0 Specification intentionally only depicts the trust triangle in one place — as an example of one typical Layer 3 trust task in the conceptual diagram in the Introduction — and only mentions the role of "issuer" in 3 places. That was deliberate because at Layer 2, the architecture is inherently peer-to-peer, i.e., the Layer 2 trust spanning protocol applies to any interaction between any two ToIP endpoint systems just like the IP protocol applies to any interaction between TCP/IP endpoints.

Net net: I don't see any changes required in the ToIP Technology Architecture V1.0 Specification, and suggest this issue be closed.

**Comment by mwherman2000** [comment]
> Regarding the images. I do not like the "anonymous" looking figures. Any depiction of people should use our ToIP images color look and feel.

These images are DIDComm Notation elements, the graphical language used to design decentralized systems in the Web 7.0 DIDComm-ARM (the equivalent of ArchiMate for decentralized systems architecture). 
Reference: https://hyperonomy.com/2022/12/18/web-7-0-didcomm-agent-architecture-reference-model-didcomm-arm-0-40-december-18-2022/

**Comment by dhh1128** [comment]
I'm just noting one way that we may be talking past each other here.

I believe Michael is using the term "credential" in a different way than the rest of us do. If we use Michael's definition of credential -- a collection of name-value pairs -- then it approximately maps to the concept of a DIDComm message and does not necessarily imply the trust triangle. Thus, it is a layer 2 construct.

Having acknowledged that possibility, I have to say that the generic definition of "credential" does not feel like a good one to use in ToIP contexts. It already has a carefully defined meaning that is different and more specific than that, and we should be consistent.

If we keep the established ToIP meaning for credential, then everything Drummond said about the trust triangle applies, and credentials in the ToIP sense are a layer-3 construct.

**Comment by mwherman2000** [comment]
> I believe Michael is using the term "credential" in a different way than the rest of us do.

To be precise, my Web 7.0 models focuses on the terms Raw Credential and Verifiable Credentials. Please reread the latest versions of my postings carefully; especially https://github.com/trustoverip/TechArch/issues/83#issuecomment-1399299927.

What you see is the evolution of a succession of more and more refined specializations of the Raw Credential Sender-Reciever Model (Layer 2) into the Verifiable Credential Sender-Reciever Model (Later 3) into the Issuer-Holder-Verifier Model (also Layer 3). ...that is, a hierarchical taxonomy of credential sender-reciever models. This is extremely powerful.
...but perhaps too detailed for the TOIP TAS documentation?

**Comment by talltree** [comment]
@mwherman2000 I don't doubt that it is very powerful — and I agree, it's too deep for the ToIP TAS spec. But I'm sure it will come up in various component specs.

**Comment by mwherman2000** [comment]
I created a new tutorial that summarizes the latest information from issues https://github.com/trustoverip/TechArch/issues/83 and https://github.com/trustoverip/TechArch/issues/84.  
If you have been following either thread, there is also some new data and graphics.  Check out
[Web 7.0 Trust Spanning Layer Framework 0.57](https://www.youtube.com/watch?v=rrFfuUHHmr4) (https://www.youtube.com/watch?v=rrFfuUHHmr4)
NOTE: It may be a few hours before YouTube has finished post-processing the video.

With this note, I'm closing both of the issues: https://github.com/trustoverip/TechArch/issues/83 and https://github.com/trustoverip/TechArch/issues/84.
