### ISSUE TITLE
Change the reference to the TSWG glossary

### ISSUE THREAD

**Issue by neiljthomson** [trustoverip/TechArch#9]
Suggest: 
To the following 
    "ToIP [Concepts and Terminology Working Group](https://wiki.trustoverip.org/pages/viewpage.action?pageId=65700) "

Add
and in the [Technology Stack Working Group](https://wiki.trustoverip.org/display/HOME/Technology+Stack+Working+Group) Technical Architecture [glossary](https://trustoverip.github.io/tswg/glossary).

**Comment by talltree** [comment]
Closed by editorial fixes in PR #66. Will be updated with new text in PR2 when full Glossary support is added.
